<a href="https://colab.research.google.com/github/Obi-chidinma2003/100-days-of-data-repository/blob/main/Day_10_selecting_rows_columns_(data_filtering).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd

VIEWING THE CONTENT OF THE DATASET.

In [68]:
path="/content/drive/MyDrive/Dataset/dairy_dataset.csv"
df=pd.read_csv(path)
df.head(10)

,Location,Total Land Area (Acres),Number Of Cows,Farm Size,Date,Product Id,Product Name,Brand,Quantity (Liters/Kg),Price Per Unit,...,Production Date,Expiration Date,Quantity Sold (Liters/Kg),Price Per Unit (Sold),Approx. Total Revenue(Inr),Customer Location,Sales Channel,Quantity In Stock (Liters/Kg),Minimum Stock Threshold (Liters/Kg),Reorder Quantity (Liters/Kg)
0,Telangana,310.84,96,Medium,"44,609.00",5,Ice Cream,Dodla Dairy,222.40,85.72,...,44557,44582,7,82.24,575.68,Madhya Pradesh,Wholesale,215,19.55,64.03
1,Uttar Pradesh,19.19,44,Large,44531,1,Milk,Amul,687.48,42.61,...,44472,44494,558,39.24,21895.92,Kerala,Wholesale,129,43.17,181.10
2,Tamil Nadu,581.69,24,Medium,44620,4,Yogurt,Dodla Dairy,503.48,36.50,...,44575,44605,256,33.81,8655.36,Madhya Pradesh,Online,247,15.10,140.83
3,Telangana,908.00,89,Small,43625,3,Cheese,Britannia Industries,823.36,26.52,...,43600,43672,601,28.92,17380.92,Rajasthan,Online,222,74.50,57.68
4,Maharashtra,861.95,21,Medium,44179,8,Buttermilk,Mother Dairy,147.77,83.85,...,44121,44132,145,83.07,12045.15,Jharkhand,Retail,2,76.02,33.40
5,Telangana,87.64,51,Medium,43472,6,Curd,Raj,593.92,85.54,...,43468,43473,74,84.75,6271.50,Gujarat,Retail,519,55.60,139.59
6,Karnataka,73.28,74,Small,44778,3,Cheese,Dynamix Dairies,757.14,36.83,...,44726,44809,410,32.66,13390.60,Karnataka,Online,347,49.82,105.86
7,Bihar,67.61,77,Medium,43510,9,Paneer,Mother Dairy,203.36,29.08,...,43471,43485,15,29.09,436.35,Haryana,Online,188,10.90,25.14
8,West Bengal,72.31,76,Medium,44045,6,Curd,Raj,949.12,22.79,...,43988,43994,860,24.77,21302.20,Jharkhand,Wholesale,89,85.71,32.03
9,Telangana,413.24,36,Large,44624,8,Buttermilk,Mother Dairy,385.64,42.08,...,44595,44604,108,46.15,4984.20,Tamil Nadu,Retail,277,93.61,66.26

**SELECTING BRAND COLUMN**

In [69]:
df["Brand"]

0                Dodla Dairy
1                       Amul
2                Dodla Dairy
3       Britannia Industries
4               Mother Dairy
                ...
4320            Mother Dairy
4321            Palle2Patnam
4322            Mother Dairy
4323                     Raj
4324            Mother Dairy
Name: Brand, Length: 4325, dtype: object

SELECTING MULTIPLE COLUMNS

In [70]:
df[["Location", "Product Name", "Brand"]]

           Location Product Name                 Brand
0         Telangana    Ice Cream           Dodla Dairy
1     Uttar Pradesh         Milk                  Amul
2        Tamil Nadu       Yogurt           Dodla Dairy
3         Telangana       Cheese  Britannia Industries
4       Maharashtra   Buttermilk          Mother Dairy
...             ...          ...                   ...
4320          Delhi         Curd          Mother Dairy
4321      Jharkhand       Yogurt          Palle2Patnam
4322     Chandigarh         Curd          Mother Dairy
4323    Maharashtra         Curd                   Raj
4324      Rajasthan         Milk          Mother Dairy

[4325 rows x 3 columns]

SELECTING THEFIRST ROW[0]

In [71]:
df.iloc[0]

Location                                    Telangana
Total Land Area (Acres)                        310.84
Number Of Cows                                     96
Farm Size                                      Medium
Date                                        44,609.00
Product Id                                          5
Product Name                                Ice Cream
Brand                                     Dodla Dairy
Quantity (Liters/Kg)                            222.4
Price Per Unit                                  85.72
Total Value                                 19064.128
Shelf Life (Days)                                  25
Storage Condition                              Frozen
Production Date                                 44557
Expiration Date                                 44582
Quantity Sold (Liters/Kg)                           7
Price Per Unit (Sold)                           82.24
Approx. Total Revenue(Inr)                     575.68
Customer Location                      Madhya Pradesh
Sales Channel                               Wholesale
Quantity In Stock (Liters/Kg)                     215
Minimum Stock Threshold (Liters/Kg)             19.55
Reorder Quantity (Liters/Kg)                    64.03
Name: 0, dtype: object

SELECTING THE 20TH ROWS

In [72]:
df.iloc[20]

Location                                  Jharkhand
Total Land Area (Acres)                      705.01
Number Of Cows                                   24
Farm Size                                     Large
Date                                          43970
Product Id                                        9
Product Name                                 Paneer
Brand                                           Raj
Quantity (Liters/Kg)                          88.69
Price Per Unit                                87.53
Total Value                               7763.0357
Shelf Life (Days)                                10
Storage Condition                      Refrigerated
Production Date                               43925
Expiration Date                               43935
Quantity Sold (Liters/Kg)                        26
Price Per Unit (Sold)                          87.3
Approx. Total Revenue(Inr)                   2269.8
Customer Location                        Chandigarh
Sales Channel                             Wholesale
Quantity In Stock (Liters/Kg)                    62
Minimum Stock Threshold (Liters/Kg)           31.49
Reorder Quantity (Liters/Kg)                 106.59
Name: 20, dtype: object

SELECTING MULTIPLE ROWS

In [74]:
df.loc[3,"Brand"]

'Britannia Industries'